# Generated by Django 2.2.24 on 2022-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='is_building_new',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Старое здание'), (None, 'Неизвестно')], default=None, null=True),
        ),
    ]
