# Generated by Django 2.2.24 on 2022-07-14 18:57

from django.db import migrations


def check_is_building_new(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    flats.filter(construction_year__gte=2015).update(is_building_new=True)
    flats.filter(construction_year__lt=2015).update(is_building_new=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_is_building_new'),
    ]

    operations = [
        migrations.RunPython(check_is_building_new),
    ]
