# Generated by Django 2.2.24 on 2022-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_is_building_new'),
    ]

    operations = [
    ]
