# Generated by Django 2.2.28 on 2022-07-20 12:22

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220716_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='is_building_new',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], db_index=True, default=None, null=True, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто поставил лайк'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца')),
                ('owners_phonenumber', models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца')),
                ('owner_normalized_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца')),
                ('flats', models.ManyToManyField(db_index=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
            options={
                'verbose_name': 'Собственник',
                'verbose_name_plural': 'Собственники',
            },
        ),
    ]
