# Generated by Django 2.2.28 on 2022-07-20 13:12

from django.db import migrations


def relate_flats2owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()

    for flat in flats:
        owner, created = Owner.objects.get_or_create(full_name=flat.owner, owners_phonenumber=flat.owners_phonenumber)
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220720_1524'),
    ]

    operations = [
        migrations.RunPython(relate_flats2owners),
    ]
