# Generated by Django 2.2.28 on 2022-07-20 13:12

from django.db import migrations


def relate_flats2owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        owners = flat.owners.all()
        for owner in owners:
            owner.flats.add(flat)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats = None
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220720_1524'),
    ]

    operations = [
        migrations.RunPython(relate_flats2owners, move_backward),
    ]
