# Generated by Django 2.2.28 on 2022-07-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_remove_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_normalized_phone',
        ),
    ]
